sudo: required
language: ruby

services:
  - docker

before_install:
  - docker pull sath89/oracle-12c
  - docker run -d -p 8080:8080 -p 1521:1521 sath89/oracle-12c

script:
  - docker ps -a