sudo: required
language: php
php:
  - '7.1'

services:
  - docker

before_install:
  - pecl install oci8
  - echo 'extension = oci8.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - composer validate --no-check-publish
  - docker pull sath89/oracle-12c
  - docker run -d -p 8080:8080 -p 1521:1521 --name oracle sath89/oracle-12c
  - sleep 30

install:
  - composer install

script:
  - docker ps -a | grep oracle12c
  - TRAVIS=true vendor/bin/phpunit